---
Name: customhtmlformroutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'customhtmlformaction//$Action/$ID/$OtherID': 'CustomHtmlForm\Control\ActionHandler'
    'customhtmlformimage//$Action/$ID/$OtherID': 'CustomHtmlForm\Control\ImageHandler'